# Default values for spark.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
spark_driver:
  mode: local
  image:
    repository: ci-dump-dcr.mfb.io/data/k8s-spark-example
    tag: to_be_overwrite
    pullPolicy: IfNotPresent
  env:
    ENV: dev
    PYTHON_FILE: /workspace/python/pi.py
  resources:
    limits:
      memory: 524Mi
    requests:
      memory: 524Mi

spark_properties: |-
  spark.master=local[6]

serviceAccount:
  create: false
  name: spark

service:
  type: ClusterIP

